version: '3'
services:
  web:
    image: wordpress:latest
    ports:
      - "8943:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jetengine
      MYSQL_USER: userjetEngine
      MYSQL_PASSWORD: root
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - todo-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "3253:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
volumes:
  todo-data:
